module Tarefa2_2022li1g008_Spec where

import LI12223
import Tarefa2_2022li1g008
import Test.HUnit

testsT2 :: Test
testsT2 = TestLabel "Testes Tarefa 3" $ test [
    "Teste 1" ~: Mapa 6 [(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),
                         (Rio 1,[Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum]),
                         (Rio (-2),[Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco]),
                         (Rio 4,[Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),
                         (Rio (-4),[Tronco,Tronco,Tronco,Nenhum,Nenhum,Tronco])]  ~=? estendeMapa (Mapa 6 [(Rio 1,[Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum]),
                                                                                                           (Rio (-2),[Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco]),
                                                                                                           (Rio 4,[Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),
                                                                                                           (Rio (-4),[Tronco,Tronco,Tronco,Nenhum,Nenhum,Tronco])]) 7,
    "Teste 2" ~: Mapa 6 [(Estrada (-1),[Nenhum,Nenhum,Nenhum,Carro,Carro,Carro]),
                         (Rio 1,[Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum]),
                         (Rio (-2),[Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco]),
                         (Rio 4,[Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),
                         (Rio (-4),[Tronco,Tronco,Tronco,Nenhum,Nenhum,Tronco])]  ~=? estendeMapa (Mapa 6 [(Rio 1,[Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum]),
                                                                                                           (Rio (-2),[Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco]),
                                                                                                           (Rio 4,[Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),
                                                                                                           (Rio (-4),[Tronco,Tronco,Tronco,Nenhum,Nenhum,Tronco])]) 23, 
    "Teste 3" ~: Mapa 6 [(Relva,[Arvore,Nenhum,Nenhum,Arvore,Arvore,Arvore]),
                         (Estrada 2,[Carro,Carro,Nenhum,Carro,Nenhum,Carro]),
                         (Estrada (-1),[Nenhum,Nenhum,Carro,Carro,Nenhum,Carro]),
                         (Estrada 1,[Nenhum,Carro,Nenhum,Carro,Nenhum,Carro]),
                         (Estrada (-1),[Carro,Nenhum,Nenhum,Carro,Carro,Nenhum]),
                         (Estrada 4,[Carro,Carro,Carro,Nenhum,Carro,Nenhum])]  ~=? estendeMapa (Mapa 6 [(Estrada 2,[Carro,Carro,Nenhum,Carro,Nenhum,Carro]),
                                                                                                        (Estrada (-1),[Nenhum,Nenhum,Carro,Carro,Nenhum,Carro]),
                                                                                                        (Estrada 1,[Nenhum,Carro,Nenhum,Carro,Nenhum,Carro]),
                                                                                                        (Estrada (-1),[Carro,Nenhum,Nenhum,Carro,Carro,Nenhum]),
                                                                                                        (Estrada 4,[Carro,Carro,Carro,Nenhum,Carro,Nenhum])]) 19,   
    "Teste 4" ~: Mapa 6 [(Relva,[Arvore,Nenhum,Arvore,Nenhum,Nenhum,Nenhum]),
                         (Estrada 2,[Carro,Carro,Nenhum,Carro,Nenhum,Carro]),
                         (Estrada (-1),[Nenhum,Nenhum,Carro,Carro,Nenhum,Carro]),
                         (Estrada 1,[Nenhum,Carro,Nenhum,Carro,Nenhum,Carro]),
                         (Estrada (-1),[Carro,Nenhum,Nenhum,Carro,Carro,Nenhum]),
                         (Estrada 4,[Carro,Carro,Carro,Nenhum,Carro,Nenhum])]  ~=? estendeMapa (Mapa 6 [(Estrada 2,[Carro,Carro,Nenhum,Carro,Nenhum,Carro]),
                                                                                                        (Estrada (-1),[Nenhum,Nenhum,Carro,Carro,Nenhum,Carro]),
                                                                                                        (Estrada 1,[Nenhum,Carro,Nenhum,Carro,Nenhum,Carro]),
                                                                                                        (Estrada (-1),[Carro,Nenhum,Nenhum,Carro,Carro,Nenhum]),
                                                                                                        (Estrada 4,[Carro,Carro,Carro,Nenhum,Carro,Nenhum])]) 2,
    "Teste 5" ~: Mapa 6 [(Estrada 1,[Carro,Carro,Nenhum,Carro,Nenhum,Carro]),
                         (Relva,[Arvore,Arvore,Arvore,Nenhum,Nenhum,Arvore]),
                         (Relva,[Nenhum,Arvore,Nenhum,Nenhum,Arvore,Arvore]),
                         (Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),
                         (Relva,[Arvore,Arvore,Arvore,Nenhum,Arvore,Nenhum]),
                         (Relva,[Arvore,Nenhum,Nenhum,Nenhum,Arvore,Arvore])] ~=? estendeMapa (Mapa 6 [(Relva,[Arvore,Arvore,Arvore,Nenhum,Nenhum,Arvore]),
                                                                                                       (Relva,[Nenhum,Arvore,Nenhum,Nenhum,Arvore,Arvore]),
                                                                                                       (Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),
                                                                                                       (Relva,[Arvore,Arvore,Arvore,Nenhum,Arvore,Nenhum]),
                                                                                                       (Relva,[Arvore,Nenhum,Nenhum,Nenhum,Arvore,Arvore])]) 95,    
    "Teste 6" ~: Mapa 6 [(Rio 4,[Nenhum,Tronco,Nenhum,Tronco,Nenhum,Tronco]),
                         (Relva,[Arvore,Arvore,Arvore,Nenhum,Nenhum,Arvore]),
                         (Relva,[Nenhum,Arvore,Nenhum,Nenhum,Arvore,Arvore]),
                         (Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),
                         (Relva,[Arvore,Arvore,Arvore,Nenhum,Arvore,Nenhum]),
                         (Relva,[Arvore,Nenhum,Nenhum,Nenhum,Arvore,Arvore])] ~=? estendeMapa (Mapa 6 [(Relva,[Arvore,Arvore,Arvore,Nenhum,Nenhum,Arvore]),
                                                                                                       (Relva,[Nenhum,Arvore,Nenhum,Nenhum,Arvore,Arvore]),
                                                                                                       (Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),
                                                                                                       (Relva,[Arvore,Arvore,Arvore,Nenhum,Arvore,Nenhum]),
                                                                                                       (Relva,[Arvore,Nenhum,Nenhum,Nenhum,Arvore,Arvore])]) 100,
    "Teste 7" ~: Mapa 4 [(Rio 4,[Nenhum,Tronco,Tronco,Tronco]),
                         (Relva,[Nenhum,Arvore,Arvore,Nenhum]),
                         (Rio (-3),[Tronco,Tronco,Nenhum,Tronco]),
                         (Rio 1,[Nenhum,Nenhum,Tronco,Nenhum]),
                         (Estrada 2,[Carro,Carro,Carro,Nenhum])] ~=? estendeMapa (Mapa 4 [(Relva,[Nenhum,Arvore,Arvore,Nenhum]),
                                                                                          (Rio (-3),[Tronco,Tronco,Nenhum,Tronco]),
                                                                                          (Rio 1,[Nenhum,Nenhum,Tronco,Nenhum]),
                                                                                          (Estrada 2,[Carro,Carro,Carro,Nenhum])]) 30, 
    "Teste 8" ~: Mapa 4 [(Rio 3,[Tronco,Nenhum,Tronco,Nenhum]),
                         (Relva,[Nenhum,Arvore,Arvore,Nenhum]),
                         (Rio (-3),[Tronco,Tronco,Nenhum,Tronco]),
                         (Rio 1,[Nenhum,Nenhum,Tronco,Nenhum]),
                         (Estrada 2,[Carro,Carro,Carro,Nenhum])] ~=? estendeMapa (Mapa 4 [(Relva,[Nenhum,Arvore,Arvore,Nenhum]),
                                                                                          (Rio (-3),[Tronco,Tronco,Nenhum,Tronco]),
                                                                                          (Rio 1,[Nenhum,Nenhum,Tronco,Nenhum]),
                                                                                          (Estrada 2,[Carro,Carro,Carro,Nenhum])]) 88, 
    "Teste 9" ~: Mapa 4 [(Rio 5,[Nenhum,Nenhum,Nenhum,Tronco]),
                         (Relva,[Nenhum,Arvore,Arvore,Nenhum]),
                         (Rio (-3),[Tronco,Tronco,Nenhum,Tronco]),
                         (Rio 1,[Nenhum,Nenhum,Tronco,Nenhum]),
                         (Estrada 2,[Carro,Carro,Carro,Nenhum])] ~=? estendeMapa (Mapa 4 [(Relva,[Nenhum,Arvore,Arvore,Nenhum]),
                                                                                          (Rio (-3),[Tronco,Tronco,Nenhum,Tronco]),
                                                                                          (Rio 1,[Nenhum,Nenhum,Tronco,Nenhum]),
                                                                                          (Estrada 2,[Carro,Carro,Carro,Nenhum])]) 0, 
    "Teste 10" ~: Mapa 4 [(Estrada 3,[Carro,Carro,Nenhum,Nenhum]),
                         (Relva,[Nenhum,Arvore,Arvore,Nenhum]),
                         (Rio (-3),[Tronco,Tronco,Nenhum,Tronco]),
                         (Rio 1,[Nenhum,Nenhum,Tronco,Nenhum]),
                         (Estrada 2,[Carro,Carro,Carro,Nenhum])] ~=? estendeMapa (Mapa 4 [(Relva,[Nenhum,Arvore,Arvore,Nenhum]),
                                                                                          (Rio (-3),[Tronco,Tronco,Nenhum,Tronco]),
                                                                                          (Rio 1,[Nenhum,Nenhum,Tronco,Nenhum]),
                                                                                          (Estrada 2,[Carro,Carro,Carro,Nenhum])]) 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    ] 