module Tarefa5_2022li1g008_Spec where

import LI12223
import Tarefa5_2022li1g008
import Test.HUnit
import Tarefa5_2022li1g008 (deslizaJogo)

testsT5 :: Test
testsT5 = TestLabel "Testes Tarefa 5" $ test [
    "Teste 1" ~: Jogo (Jogador (1,2)) (Mapa 6 [(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),
                                      (Rio 1,[Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum]),
                                      (Rio (-2),[Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco]),
                                      (Rio 4,[Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco])])  ~=? deslizaJogo 7 (Jogo (Jogador (1,1)) (Mapa 6 [(Rio 1,[Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum]),
                                                                                                                                    (Rio (-2),[Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco]),
                                                                                                                                    (Rio 4,[Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),
                                                                                                                                    (Rio (-4),[Tronco,Tronco,Tronco,Nenhum,Nenhum,Tronco])])) ,
    "Teste 2" ~: Jogo (Jogador (1,2)) (Mapa 6 [(Estrada (-1),[Nenhum,Nenhum,Nenhum,Carro,Carro,Carro]),
                                      (Rio 1,[Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum]),
                                      (Rio (-2),[Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco]),
                                      (Rio 4,[Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco])])  ~=? deslizaJogo 23 (Jogo (Jogador (1,1)) (Mapa 6 [(Rio 1,[Tronco,Tronco,Tronco,Nenhum,Tronco,Nenhum]),
                                                                                                                                     (Rio (-2),[Nenhum,Tronco,Tronco,Nenhum,Tronco,Tronco]),
                                                                                                                                     (Rio 4,[Tronco,Nenhum,Tronco,Tronco,Nenhum,Tronco]),
                                                                                                                                     (Rio (-4),[Tronco,Tronco,Tronco,Nenhum,Nenhum,Tronco])])) , 
    "Teste 3" ~: Jogo (Jogador (1,2)) (Mapa 6 [(Relva,[Arvore,Nenhum,Nenhum,Arvore,Arvore,Arvore]),
                                      (Estrada 2,[Carro,Carro,Nenhum,Carro,Nenhum,Carro]),
                                      (Estrada (-1),[Nenhum,Nenhum,Carro,Carro,Nenhum,Carro]),
                                      (Estrada 1,[Nenhum,Carro,Nenhum,Carro,Nenhum,Carro]),
                                      (Estrada (-1),[Carro,Nenhum,Nenhum,Carro,Carro,Nenhum])])  ~=? deslizaJogo 19 (Jogo (Jogador (1,1)) (Mapa 6 [(Estrada 2,[Carro,Carro,Nenhum,Carro,Nenhum,Carro]),
                                                                                                                                         (Estrada (-1),[Nenhum,Nenhum,Carro,Carro,Nenhum,Carro]),
                                                                                                                                         (Estrada 1,[Nenhum,Carro,Nenhum,Carro,Nenhum,Carro]),
                                                                                                                                         (Estrada (-1),[Carro,Nenhum,Nenhum,Carro,Carro,Nenhum]),
                                                                                                                                         (Estrada 4,[Carro,Carro,Carro,Nenhum,Carro,Nenhum])])) ,   
    "Teste 4" ~: Jogo (Jogador (1,2)) (Mapa 6 [(Relva,[Arvore,Nenhum,Arvore,Nenhum,Nenhum,Nenhum]),
                                      (Estrada 2,[Carro,Carro,Nenhum,Carro,Nenhum,Carro]),
                                      (Estrada (-1),[Nenhum,Nenhum,Carro,Carro,Nenhum,Carro]),
                                      (Estrada 1,[Nenhum,Carro,Nenhum,Carro,Nenhum,Carro]),
                                      (Estrada (-1),[Carro,Nenhum,Nenhum,Carro,Carro,Nenhum])])  ~=? deslizaJogo 2 (Jogo (Jogador (1,1)) (Mapa 6 [(Estrada 2,[Carro,Carro,Nenhum,Carro,Nenhum,Carro]),
                                                                                                                                        (Estrada (-1),[Nenhum,Nenhum,Carro,Carro,Nenhum,Carro]),
                                                                                                                                        (Estrada 1,[Nenhum,Carro,Nenhum,Carro,Nenhum,Carro]),
                                                                                                                                        (Estrada (-1),[Carro,Nenhum,Nenhum,Carro,Carro,Nenhum]),
                                                                                                                                        (Estrada 4,[Carro,Carro,Carro,Nenhum,Carro,Nenhum])])) ,
    "Teste 5" ~: Jogo (Jogador (1,2)) (Mapa 6 [(Estrada 1,[Carro,Carro,Nenhum,Carro,Nenhum,Carro]),
                                              (Relva,[Arvore,Arvore,Arvore,Nenhum,Nenhum,Arvore]),
                                              (Relva,[Nenhum,Arvore,Nenhum,Nenhum,Arvore,Arvore]),
                                              (Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),
                                              (Relva,[Arvore,Arvore,Arvore,Nenhum,Arvore,Nenhum])]) ~=? deslizaJogo 95 (Jogo (Jogador (1,1)) (Mapa 6 [(Relva,[Arvore,Arvore,Arvore,Nenhum,Nenhum,Arvore]),
                                                                                                                                            (Relva,[Nenhum,Arvore,Nenhum,Nenhum,Arvore,Arvore]),
                                                                                                                                            (Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),
                                                                                                                                            (Relva,[Arvore,Arvore,Arvore,Nenhum,Arvore,Nenhum]),
                                                                                                                                            (Relva,[Arvore,Nenhum,Nenhum,Nenhum,Arvore,Arvore])])) ,    
    "Teste 6" ~: Jogo (Jogador (1,2)) (Mapa 6 [(Rio 4,[Nenhum,Tronco,Nenhum,Tronco,Nenhum,Tronco]),
                                      (Relva,[Arvore,Arvore,Arvore,Nenhum,Nenhum,Arvore]),
                                      (Relva,[Nenhum,Arvore,Nenhum,Nenhum,Arvore,Arvore]),
                                      (Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),
                                      (Relva,[Arvore,Arvore,Arvore,Nenhum,Arvore,Nenhum])]) ~=? deslizaJogo 100 (Jogo (Jogador (1,1)) (Mapa 6 [(Relva,[Arvore,Arvore,Arvore,Nenhum,Nenhum,Arvore]),
                                                                                                                                     (Relva,[Nenhum,Arvore,Nenhum,Nenhum,Arvore,Arvore]),
                                                                                                                                     (Relva,[Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore]),
                                                                                                                                     (Relva,[Arvore,Arvore,Arvore,Nenhum,Arvore,Nenhum]),
                                                                                                                                     (Relva,[Arvore,Nenhum,Nenhum,Nenhum,Arvore,Arvore])])),
    "Teste 7" ~: Jogo (Jogador (1,2)) (Mapa 4 [(Rio 4,[Nenhum,Tronco,Tronco,Tronco]),
                                      (Relva,[Nenhum,Arvore,Arvore,Nenhum]),
                                      (Rio (-3),[Tronco,Tronco,Nenhum,Tronco]),
                                      (Rio 1,[Nenhum,Nenhum,Tronco,Nenhum])]) ~=? deslizaJogo 30 (Jogo (Jogador (1,1)) (Mapa 4 [(Relva,[Nenhum,Arvore,Arvore,Nenhum]),
                                                                                                                      (Rio (-3),[Tronco,Tronco,Nenhum,Tronco]),
                                                                                                                      (Rio 1,[Nenhum,Nenhum,Tronco,Nenhum]),
                                                                                                                      (Estrada 2,[Carro,Carro,Carro,Nenhum])])) , 
    "Teste 8" ~: Jogo (Jogador (1,2)) (Mapa 4 [(Rio 3,[Tronco,Nenhum,Tronco,Nenhum]),
                                      (Relva,[Nenhum,Arvore,Arvore,Nenhum]),
                                      (Rio (-3),[Tronco,Tronco,Nenhum,Tronco]),
                                      (Rio 1,[Nenhum,Nenhum,Tronco,Nenhum])]) ~=? deslizaJogo 88 (Jogo (Jogador (1,1)) (Mapa 4 [(Relva,[Nenhum,Arvore,Arvore,Nenhum]),
                                                                                                                      (Rio (-3),[Tronco,Tronco,Nenhum,Tronco]),
                                                                                                                      (Rio 1,[Nenhum,Nenhum,Tronco,Nenhum]),
                                                                                                                      (Estrada 2,[Carro,Carro,Carro,Nenhum])])) , 
    "Teste 9" ~: Jogo (Jogador (1,2)) (Mapa 4 [(Rio 5,[Nenhum,Nenhum,Nenhum,Tronco]),
                                      (Relva,[Nenhum,Arvore,Arvore,Nenhum]),
                                      (Rio (-3),[Tronco,Tronco,Nenhum,Tronco]),
                                      (Rio 1,[Nenhum,Nenhum,Tronco,Nenhum])]) ~=? deslizaJogo 0 (Jogo (Jogador (1,1)) (Mapa 4 [(Relva,[Nenhum,Arvore,Arvore,Nenhum]),
                                                                                                                      (Rio (-3),[Tronco,Tronco,Nenhum,Tronco]),
                                                                                                                      (Rio 1,[Nenhum,Nenhum,Tronco,Nenhum]),
                                                                                                                      (Estrada 2,[Carro,Carro,Carro,Nenhum])])) , 
    "Teste 10" ~: Jogo (Jogador (1,2)) (Mapa 4 [(Estrada 3,[Carro,Carro,Nenhum,Nenhum]),
                                       (Relva,[Nenhum,Arvore,Arvore,Nenhum]),
                                       (Rio (-3),[Tronco,Tronco,Nenhum,Tronco]),
                                       (Rio 1,[Nenhum,Nenhum,Tronco,Nenhum])]) ~=? deslizaJogo 1 (Jogo (Jogador (1,1)) (Mapa 4 [(Relva,[Nenhum,Arvore,Arvore,Nenhum]),
                                                                                                                      (Rio (-3),[Tronco,Tronco,Nenhum,Tronco]),
                                                                                                                      (Rio 1,[Nenhum,Nenhum,Tronco,Nenhum]),
                                                                                                                      (Estrada 2,[Carro,Carro,Carro,Nenhum])]))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    ] 